#######################################
# Generated By CMake Generator v1.2.7 #
#######################################


if(NOT DEFINED CMAKE_INSTALL_PREFIX)
    set(CMAKE_INSTALL_PREFIX "/usr/local" CACHE INTERNAL "")
endif()

if(NOT DEFINED CPACK_PACKAGING_INSTALL_PREFIX)
    set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}" CACHE INTERNAL "")
endif()


set(redefine_option_list
    CMAKE_CXX_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_RELEASE CMAKE_CXX_FLAGS_DEBUG
    CMAKE_C_FLAGS_RELWITHDEBINFO CMAKE_C_FLAGS_RELEASE CMAKE_C_FLAGS_DEBUG
)
foreach(target ${redefine_option_list})
    string(REGEX REPLACE "(\-g[0-3]?|\-O[0-3])" "" ${target} "${${target}}")
endforeach()


unset(header_file_list)
foreach(target_directory ${header_directory_list})
    file(GLOB_RECURSE tmp_list CONFIGURE_DEPENDS "${target_directory}/*.h*")
    list(APPEND header_file_list ${tmp_list})
endforeach()

unset(source_file_list)
foreach(target_directory ${source_directory_list})
    file(GLOB_RECURSE tmp_list CONFIGURE_DEPENDS "${target_directory}/*.c*" "${target_directory}/*.s")
    list(APPEND source_file_list ${tmp_list})
endforeach()

foreach(target_pattern ${source_exclude_pattern})
    list(FILTER source_file_list EXCLUDE REGEX "${target_pattern}")
endforeach()

set(GITSUBREPO_FILE_PATH "${CMAKE_CURRENT_LIST_DIR}/.gitrepo")
if(EXISTS ${GITSUBREPO_FILE_PATH})
    execute_process(COMMAND awk "/commit/ {print $3}" ${GITSUBREPO_FILE_PATH} OUTPUT_VARIABLE COMMIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE)
elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/.git")
    find_package(Git)
    if(Git_FOUND)
        execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD OUTPUT_VARIABLE COMMIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    endif()
endif()


set(SYSTEMD_SERVICE_CONFIG_NAME ${CMAKE_CURRENT_LIST_DIR}/extra/systemd.service.in)
if(EXISTS ${SYSTEMD_SERVICE_CONFIG_NAME})
    if(NOT DEFINED SYSTEMD_SERVICE_NAME)
        string(TOLOWER ${PROJECT_NAME} SYSTEMD_SERVICE_NAME)
    endif()
    configure_file(${SYSTEMD_SERVICE_CONFIG_NAME} ${SYSTEMD_SERVICE_NAME}.service @ONLY)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${SYSTEMD_SERVICE_NAME}.service DESTINATION /usr/lib/systemd/system)
endif()


if(NOT CPack_CMake_INCLUDED)
    set(CPACK_GENERATOR "DEB;RPM")

    set(CAPCK_PREINST_SCRIPT_FILE ${CMAKE_CURRENT_BINARY_DIR}/package/preinst)
    set(CAPCK_POSTINST_SCRIPT_FILE ${CMAKE_CURRENT_BINARY_DIR}/package/postinst)
    set(CAPCK_PRERM_SCRIPT_FILE ${CMAKE_CURRENT_BINARY_DIR}/package/prerm)
    set(CAPCK_POSTRM_SCRIPT_FILE ${CMAKE_CURRENT_BINARY_DIR}/package/postrm)

    set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION True)
    set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
        ${CAPCK_PREINST_SCRIPT_FILE} ${CAPCK_POSTINST_SCRIPT_FILE} ${CAPCK_PRERM_SCRIPT_FILE} ${CAPCK_POSTRM_SCRIPT_FILE}
    )
    set(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE ${CAPCK_PREINST_SCRIPT_FILE})
    set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE ${CAPCK_POSTINST_SCRIPT_FILE})
    set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE ${CAPCK_PRERM_SCRIPT_FILE})
    set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE ${CAPCK_POSTRM_SCRIPT_FILE})
    set(CPACK_RPM_RELOCATION_PATHS 
        /usr/lib
        /etc
        /opt
    )
    set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION
        /usr/local
        /usr/local/bin
        /usr/local/include
        /usr/local/lib
        /usr/local/lib/pkgconfig
        /usr/local/share
        /usr/local/share/doc
        /usr/local/src
        /usr/lib/systemd
        /usr/lib/systemd/system
        /usr/src
        /opt
    )

    if(NOT DEFINED CPACK_DEBIAN_PACKAGE_ARCHITECTURE)
        execute_process(COMMAND dpkg --print-architecture OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()
    if(NOT DEFINED CPACK_RPM_PACKAGE_ARCHITECTURE)
        execute_process(COMMAND uname -m OUTPUT_VARIABLE CPACK_RPM_PACKAGE_ARCHITECTURE OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()

    string(TOLOWER ${PROJECT_NAME} CPACK_PACKAGE_NAME)
    string(REPLACE _ - CPACK_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
    set(CPACK_DEBIAN_FILE_NAME ${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE})
    set(CPACK_RPM_FILE_NAME ${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CPACK_RPM_PACKAGE_ARCHITECTURE})
    include(CPack)
    configure_file(${CMAKE_CURRENT_LIST_DIR}/extra/package/preinst.in package/preinst @ONLY)
    configure_file(${CMAKE_CURRENT_LIST_DIR}/extra/package/postinst.in package/postinst @ONLY)
    configure_file(${CMAKE_CURRENT_LIST_DIR}/extra/package/prerm.in package/prerm @ONLY)
    configure_file(${CMAKE_CURRENT_LIST_DIR}/extra/package/postrm.in package/postrm @ONLY)
endif()


find_package(Doxygen)
if(DOXYGEN_FOUND)
    set(DOXYGEN_OUTPUT_DESC
        "[ Documentation Generate Complete ]"
        "    HTML: ${CMAKE_CURRENT_BINARY_DIR}/docs/html/index.html"
    )
    option(SKIP_PDF "Skip PDF Document Generate" 0)
    if(SKIP_PDF)
        set(PRINT_PAGE_FLAG_STR "SKIP_PDF=1")
    else()
        list(APPEND DOXYGEN_OUTPUT_DESC "    PDF : ${CMAKE_CURRENT_BINARY_DIR}/docs/html/print.pdf")
    endif()
    if(NOT DOXYGEN_INPUT_OVERRIDE)
        file(GLOB MARKDOWN_FILES "${CMAKE_CURRENT_LIST_DIR}/*.md")
        set(doxygen_mainpage "${CMAKE_CURRENT_LIST_DIR}/README.md")
        string(REPLACE ";" " " doxygen_input_list "${MARKDOWN_FILES} ${CMAKE_CURRENT_LIST_DIR}/docs ${source_directory_list} ${header_directory_list}")
        string(REPLACE ";" " " doxygen_exclude_list "${docs_exclude_pattern}")
    else()
        separate_arguments(DOXYGEN_INPUT_OVERRIDE)
        list(GET DOXYGEN_INPUT_OVERRIDE 0 doxygen_mainpage)
        string(REPLACE ";" " " doxygen_input_list "${DOXYGEN_INPUT_OVERRIDE}")
    endif()

    string(REPLACE _ " " DOXYGEN_PROJECT_NAME ${CMAKE_PROJECT_NAME})
    configure_file(${CMAKE_CURRENT_LIST_DIR}/extra/doxygen/Doxyfile.in ${PROJECT_NAME}.doxygen @ONLY)
    add_custom_target(doxygen_${PROJECT_NAME} WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMENT "Documentation Generate"
        COMMAND ${DOXYGEN_EXECUTABLE} ${PROJECT_NAME}.doxygen
        COMMAND /usr/local/share/doxygen_template/util/var_replace.py docs
        COMMAND ${PRINT_PAGE_FLAG_STR} /usr/local/share/doxygen_template/util/print_page_generate.py docs
        COMMAND /usr/local/share/doxygen_template/util/page_navigation_generate.py docs
        COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --cyan ${DOXYGEN_OUTPUT_DESC}
    )
    if(NOT DOCS_AUTO_BUILD_DISABLE AND (("${CMAKE_BUILD_TYPE}" STREQUAL "Release") OR ("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")))
        add_custom_target(docs_${PROJECT_NAME} ALL DEPENDS doxygen_${PROJECT_NAME})
        if(NOT DOCS_INSTALL_DISABLE)
            install(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/docs/ DESTINATION share/doc/${PROJECT_NAME})
        endif()
    endif()
else()
    message("Doxygen need to be installed to generate the doxygen documentation")
endif()


