set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
set(CPACK_RPM_PACKAGE_ARCHITECTURE x86_64)

#Optional
#set(CMAKE_SYSROOT "")

if(NOT "${CMAKE_SYSROOT}" STREQUAL "")
    set(SYSROOT_TARGET_NAME "x86_64-linux-gnu")
endif()

set(TOOLCHAIN_PREFIX "x86_64-linux-gnu-")

set(SIZE_OPTIMIZE_ENABLE FALSE)

include(${CMAKE_CURRENT_LIST_DIR}/toolchain_common.cmake)
