set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)
set(CPACK_RPM_PACKAGE_ARCHITECTURE aarch64)

#Optional
#set(CMAKE_SYSROOT "")

if(NOT "${CMAKE_SYSROOT}" STREQUAL "")
    set(SYSROOT_TARGET_NAME "aarch64-linux-gnu")
endif()

set(TOOLCHAIN_PREFIX "aarch64-linux-gnu-")

set(SIZE_OPTIMIZE_ENABLE FALSE)

include(${CMAKE_CURRENT_LIST_DIR}/toolchain_common.cmake)
